# Generated by Django 5.2.14 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome da Empresa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome de Contato')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('industry', models.CharField(choices=[('tech', 'Tecnologia'), ('finance', 'Finanças'), ('retail', 'Varejo'), ('manufacturing', 'Manufatura'), ('services', 'Serviços'), ('education', 'Educação'), ('healthcare', 'Saúde'), ('other', 'Outro')], default='other', max_length=50, verbose_name='Setor')),
                ('client_type', models.CharField(choices=[('logo_only', 'Apenas Logo'), ('with_testimonial', 'Com Depoimento'), ('partner', 'Parceiro')], default='logo_only', max_length=30, verbose_name='Tipo de Cliente')),
                ('size', models.CharField(blank=True, help_text='Ex: 1-50, 51-200, 200+', max_length=50, null=True, verbose_name='Tamanho da Empresa')),
                ('logo', models.ImageField(upload_to='clients/logos/%Y/%m/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='clients/banners/%Y/%m/', verbose_name='Banner')),
                ('employees_trained', models.PositiveIntegerField(default=0, verbose_name='Funcionários Treinados')),
                ('partnership_start', models.DateField(blank=True, null=True, verbose_name='Início da Parceria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Empresa Cliente',
                'verbose_name_plural': 'Empresas Clientes',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='clients_cli_is_acti_20ee0e_idx'), models.Index(fields=['industry'], name='clients_cli_industr_716df1_idx')],
            },
        ),
    ]
