# Generated by Django 5.2.14 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, unique=True, verbose_name='Pergunta')),
                ('answer', models.TextField(help_text='Resposta completa para a pergunta', verbose_name='Resposta')),
                ('category', models.CharField(choices=[('general', 'Geral'), ('home', 'Home'), ('kids', 'Kids/Crianças'), ('empresas', 'Empresas'), ('pricing', 'Preços'), ('metodologia', 'Metodologia')], default='general', max_length=50, verbose_name='Categoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('keywords', models.CharField(blank=True, help_text='Separadas por vírgula para SEO', max_length=200, null=True, verbose_name='Palavras-chave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='faqs_faq_categor_915876_idx')],
                'unique_together': {('category', 'question')},
            },
        ),
    ]
