[pytest]
DJANGO_SETTINGS_MODULE = beeu_api.core.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts =
    --strict-markers
    --tb=short
    --disable-warnings
    -v
testpaths =
    beeu_api
