# Generated by Django 5.2.14 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: SABE_INGLES, PROGRAMADOR, DESIGNER', max_length=100, unique=True, verbose_name='Nome da Tag')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tag de Professor',
                'verbose_name_plural': 'Tags de Professores',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('bio', models.TextField(help_text='Descrição breve do professor', verbose_name='Biografia')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professors/photos/%Y/%m/', verbose_name='Foto do Professor')),
                ('specialization', models.CharField(blank=True, help_text='Ex: Business English, Kids, TOEFL', max_length=200, null=True, verbose_name='Especialização')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Anos de Experiência')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Certificações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('max_students', models.PositiveIntegerField(default=10, verbose_name='Máximo de Alunos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tags', models.ManyToManyField(blank=True, to='professors.professortag', verbose_name='Habilidades/Tags')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['first_name'],
                'indexes': [models.Index(fields=['is_active'], name='professors__is_acti_118325_idx'), models.Index(fields=['specialization'], name='professors__special_a6abe5_idx')],
            },
        ),
    ]
