# Generated by Django 5.2.14 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('students', 'Número de Alunos'), ('companies', 'Número de Empresas'), ('success_rate', 'Taxa de Sucesso (%)'), ('avg_time_fluency', 'Tempo Médio para Fluência (meses)'), ('satisfaction_rate', 'Taxa de Satisfação (%)'), ('teachers', 'Número de Professores'), ('years_in_market', 'Anos de Mercado'), ('countries', 'Países Atendidos'), ('weekly_progress', 'Progresso Semanal (%)'), ('rating', 'Avaliação (0-5)'), ('reviews_count', 'Número de Avaliações'), ('custom', 'Customizado')], max_length=50, verbose_name='Tipo de Métrica')),
                ('label', models.CharField(help_text='Texto exibido ao lado do número', max_length=200, verbose_name='Rótulo')),
                ('value', models.CharField(help_text='Pode ser número, percentual, ou texto (ex: 98%, 1.200, 6 meses)', max_length=100, verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('page', models.CharField(choices=[('home', 'Home'), ('kids', 'Kids'), ('empresas', 'Empresas'), ('todas', 'Todas as Páginas')], default='home', max_length=20, verbose_name='Página')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('section', models.CharField(blank=True, help_text='Ex: HomeStats, Differentiators', max_length=100, null=True, verbose_name='Seção')),
                ('icon_name', models.CharField(blank=True, help_text='Lucide React icon name', max_length=100, null=True, verbose_name='Nome do Ícone')),
                ('color', models.CharField(default='primary', help_text='primary, navy, gold, etc', max_length=20, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['page', 'section', 'order'],
                'indexes': [models.Index(fields=['page', 'is_active'], name='statistics__page_065e89_idx'), models.Index(fields=['stat_type'], name='statistics__stat_ty_0146df_idx')],
                'unique_together': {('stat_type', 'page', 'section')},
            },
        ),
    ]
