# Generated by Django 5.2.14 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Primeiro nome do usuário', max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(help_text='Sobrenome do usuário', max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(help_text='E-mail único para contato', max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Número de telefone para contato', max_length=20, verbose_name='Telefone')),
                ('phone_type', models.CharField(choices=[('celular', 'Celular'), ('fixo', 'Fixo')], default='celular', max_length=10, verbose_name='Tipo de Telefone')),
                ('audience', models.CharField(choices=[('self', 'Para mim'), ('other', 'Para outra pessoa')], help_text='Para quem é o curso: self (para ele) ou other (para outra pessoa)', max_length=10, verbose_name='Audiência')),
                ('age_range', models.CharField(choices=[('17_under', '17 anos ou -'), ('18_24', '18-24 anos'), ('25_34', '25-34 anos'), ('35_over', '35 anos ou +')], max_length=20, verbose_name='Faixa Etária')),
                ('page_origin', models.CharField(choices=[('home', 'Home'), ('kids', 'Para Seu Filho'), ('empresas', 'Empresas'), ('outro', 'Outro')], default='home', max_length=20, verbose_name='Página de Origem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('qualificado', 'Qualificado'), ('perdido', 'Perdido'), ('convertido', 'Convertido')], default='novo', max_length=20, verbose_name='Status do Lead')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx')],
            },
        ),
    ]
