# Generated by Django 5.2.14 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Texto do depoimento do cliente', verbose_name='Depoimento')),
                ('author_name', models.CharField(help_text='Nome completo de quem deu o depoimento', max_length=150, verbose_name='Nome do Autor')),
                ('author_role', models.CharField(help_text='Profissão ou cargo do autor', max_length=150, verbose_name='Profissão/Cargo')),
                ('featured', models.BooleanField(default=False, help_text='Mostrar em destaque na página', verbose_name='Destaque')),
                ('page_origin', models.CharField(choices=[('home', 'Home'), ('empresas', 'Empresas'), ('kids', 'Kids'), ('todas', 'Todas as Páginas')], default='home', max_length=20, verbose_name='Página de Origem')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/%Y/%m/', verbose_name='Foto do Autor')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na página (0 = não mostrado)', verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['featured', 'page_origin'], name='testimonial_feature_5628ed_idx'), models.Index(fields=['is_active'], name='testimonial_is_acti_6bc8bb_idx')],
            },
        ),
    ]
